<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./9MM.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/9MM.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0.15, 0.13, 0.14]} rotation={[-Math.PI / 2, 0, 0.01]} scale={0}>
      <T.Group position={[-22.6, -3.54, 37.97]} rotation={[0, 0, 0.19]}>
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_91'].geometry}
          material={gltf.materials['Bella 1']}
          position={[2.64, 87.91, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_92'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_58'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_59'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_60'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_61'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_62'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_63'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_64'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_65'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_66'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_67'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_68'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_69'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_70'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_71'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_72'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_73'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_74'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_75'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_76'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_77'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_78'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_79'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_80'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_81'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_82'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_83'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_84'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_85'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_86'].geometry}
          material={gltf.materials['Bella 1']}
          position={[3.51, -13.69, 21.35]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_87'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_88'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_89'].geometry}
          material={gltf.materials['Bella 1']}
          position={[12.18, 87.91, -181.85]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </T.Group>
      <T.Group position={[-24.29, 10.58, 9.14]} rotation={[0, 0, 0.19]}>
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_53'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_54'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_3'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_4'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_5'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_6'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_7'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_8'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_9'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_10'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_11'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_12'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_13'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_14'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_15'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_16'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_17'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_18'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_19'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_20'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_21'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_22'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_23'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_24'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_25'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_26'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_27'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_28'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_29'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_30'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_31'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_32'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_33'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_34'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_35'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_36'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_37'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_38'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_39'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_40'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_41'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_42'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_44'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_45'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_46'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[1.98, 73.36, 44.03]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_47'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['Merged_Objects_1_-_piece_48'].geometry}
          material={gltf.materials['Titanium Satin']}
          position={[11.2, 73.36, -153.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Barrel.geometry}
        material={gltf.materials['Bella 1']}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Magazine_catch.geometry}
        material={gltf.materials.Bella}
        position={[-14.59, 11.89, 12.29]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Receiver.geometry}
        material={gltf.materials.Bella}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Magazine_Merged.geometry}
        material={gltf.materials.Bella}
        position={[-26.99, 31.26, -49.87]}
        rotation={[0, 0, 0.19]}
      />
      <T.Mesh
        geometry={gltf.nodes.recoil_spring_assembly.geometry}
        material={gltf.materials.Bella}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Spring_Assembly.geometry}
        material={gltf.materials.Bella}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Slide_catch_lever.geometry}
        material={gltf.materials.Bella}
        position={[-18.92, -8.73, 49.58]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Takedown_lever.geometry}
        material={gltf.materials.Bella}
        position={[585.78, 82.2, 43.77]}
        rotation={[-0.02, 0, 0.19]}
      />
      <T.Mesh
        geometry={gltf.nodes.Takedown_Safety_Lever.geometry}
        material={gltf.materials.Bella}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Trigger.geometry}
        material={gltf.materials['Gold 0']}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body.geometry}
        material={gltf.materials.Bella}
        position={[-15.56, -22.17, 41.33]}
        rotation={[Math.PI / 2, 0.2, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Reciever_Pin.geometry}
        material={gltf.materials.Bella}
        position={[-27.05, 85.1, -143.88]}
        rotation={[Math.PI / 2, 0.19, 0]}
      />
    </T.Group>
    <T.PerspectiveCamera
      makeDefault={false}
      far={60.75}
      near={0.01}
      fov={35}
      position={[1.12, 0.08, -0.15]}
      rotation={[3.01, 1.27, -3.02]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
